runtime: nodejs14

handlers:
  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: \1
    upload: (.*\.(gif|png|jpg|css|js)(|\.map))$

  - url: /.*
    static_files: index.html
    upload: index.html
